EXPORT_NAME_MAPPER = {
    "cls_mv3.yaml": "cls_mobilenet_v3_small_100_model",
    "abinet_resnet45_en.yaml": "abinet",
    "crnn_resnet34.yaml": "crnn_resnet34",
    "crnn_resnet34_ch.yaml": "crnn_resnet34_ch",
    "crnn_vgg7.yaml": "crnn_vgg7",
    "db_mobilenetv3_icdar15.yaml": "dbnet_mobilenetv3",
    "db_r18_ctw1500.yaml": "dbnet_resnet18",
    "db_r18_icdar15.yaml": "dbnet_resnet18",
    "db_r18_mlt2017.yaml": "dbnet_resnet18",
    "db_r18_synthtext.yaml": "dbnet_resnet18",
    "db_r18_td500.yaml": "dbnet_resnet18",
    "db_r18_totaltext.yaml": "dbnet_resnet18",
    "dbpp_r50_icdar15.yaml": "dbnetpp_resnet50",
    "db_r50_ctw1500.yaml": "dbnet_resnet50",
    "db_r50_icdar15.yaml": "dbnet_resnet50",
    "db_r50_mlt2017.yaml": "dbnet_resnet50",
    "db_r50_synthtext.yaml": "dbnet_resnet50",
    "db_r50_td500.yaml": "dbnet_resnet50",
    "db_r50_totaltext.yaml": "dbnet_resnet50",
    "east_mobilenetv3_icdar15.yaml": "east_mobilenetv3",
    "east_r50_icdar15.yaml": "east_resnet50",
    "fce_icdar15.yaml": "fcenet_resnet50",
    "pse_mv3_icdar15.yaml": "psenet_mobilenetv3",
    "pse_r152_ctw1500.yaml": "psenet_resnet152",
    "pse_r152_icdar15.yaml": "psenet_resnet152",
    "pse_r50_icdar15.yaml": "psenet_resnet50",
    "ser_layoutxlm_xfund_zh.yaml": "layoutxlm_ser",
    "master_resnet31.yaml": "master_resnet31",
    "rare_resnet34.yaml": "rare_resnet34",
    "rare_resnet34_ch.yaml": "rare_resnet34_ch",
    "robustscanner_resnet31.yaml": "robustscanner_resnet31",
    "svtr_ppocrv3_ch.yaml": "svtr_ppocrv3_ch",
    "svtr_tiny.yaml": "svtr_tiny",
    "svtr_tiny_ch.yaml": "svtr_tiny_ch",
    "visionlan_resnet45_LA.yaml": "visionlan_resnet45",
    "visionlan_resnet45_LF_1.yaml": "visionlan_resnet45",
    "visionlan_resnet45_LF_2.yaml": "visionlan_resnet45"
}

SERVABLE_CONFIGS_MAPPER = {
    "cls_mv3.yaml": "cls_common_servable_config",
    "abinet_resnet45_en.yaml": "rec_abinet_servable_config",
    "crnn_resnet34.yaml": "rec_common_servable_config",
    "crnn_resnet34_ch.yaml": "rec_common_servable_config",
    "crnn_vgg7.yaml": "rec_common_servable_config",
    "db_mobilenetv3_icdar15.yaml": "det_db_servable_config",
    "db_r18_ctw1500.yaml": "det_db_servable_config",
    "db_r18_icdar15.yaml": "det_db_servable_config",
    "db_r18_mlt2017.yaml": "det_db_servable_config",
    "db_r18_synthtext.yaml": "det_db_servable_config",
    "db_r18_td500.yaml": "det_db_servable_config",
    "db_r18_totaltext.yaml": "det_db_servable_config",
    # "dbpp_r50_icdar15.yaml": "dbnetpp_resnet50",  # todo: 检查这个
    "db_r50_ctw1500.yaml": "det_db_servable_config",
    "db_r50_icdar15.yaml": "det_db_servable_config",
    "db_r50_mlt2017.yaml": "det_db_servable_config",
    "db_r50_synthtext.yaml": "det_db_servable_config",
    "db_r50_td500.yaml": "det_db_servable_config",
    "db_r50_totaltext.yaml": "det_db_servable_config",
    "east_mobilenetv3_icdar15.yaml": "det_east_servable_config",
    "east_r50_icdar15.yaml": "det_east_servable_config",
    "fce_icdar15.yaml": "det_fce_servable_config",
    "pse_mv3_icdar15.yaml": "det_pse_servable_config",
    "pse_r152_ctw1500.yaml": "det_pse_servable_config",
    "pse_r152_icdar15.yaml": "det_pse_servable_config",
    "pse_r50_icdar15.yaml": "det_pse_servable_config",
    # "ser_layoutxlm_xfund_zh.yaml": "layoutxlm_ser",  # todo: 检查这个
    # "master_resnet31.yaml": "master_resnet31",  # todo: 检查这个
    "rare_resnet34.yaml": "rec_common_servable_config",
    "rare_resnet34_ch.yaml": "rec_common_servable_config",
    "robustscanner_resnet31.yaml": "rec_common_servable_config",
    "svtr_ppocrv3_ch.yaml": "rec_common_servable_config",
    "svtr_tiny.yaml": "rec_common_servable_config",
    "svtr_tiny_ch.yaml": "rec_common_servable_config",
    "visionlan_resnet45_LA.yaml": "rec_common_servable_config",
    "visionlan_resnet45_LF_1.yaml": "rec_common_servable_config",
    "visionlan_resnet45_LF_2.yaml": "rec_common_servable_config"
}
